FROM node:23-alpine3.19

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies

COPY package*.json ./
RUN npm install --only=production

# Bundle app source
COPY . .
EXPOSE 8080

ENTRYPOINT [ "node", "index.mjs" ]